# This is a basic workflow to help you get started with Actions

name: flake8-lint

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main, feat/deployment ]
  pull_request:
    branches: [ main, feat/deployment ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: flake8 Lint
        uses: py-actions/flake8@v1
        with:
          ignore: "F401"
          exclude: "./api/*/migrations/*,.git,.gitignore,.env,*.rdb,./requirement/*"
          max-line-length: "120"
